
export let categorias = [
    { id: 0, name: 'Fones e Headsets' },
    { id: 1, name: 'Celulares e Telefones' },
    { id: 2, name: 'Informatica' },
    { id: 3, name: 'Video game' },
    { id: 4, name: 'Eletronicos' },
    { id: 5, name: 'Automotivos' },
    { id: 6, name: 'Relogios E Joias' },
    { id: 7, name: 'Audio e Som' },
    { id: 8, name: 'Smartwacth' },
    { id: 9, name: 'Bebês e Crianças' },
    { id: 10, name: 'Ferramentas' },
    { id: 11, name: 'Casa e Cozinha' },
    { id: 12, name: 'Moda e Acessorios' },
    { id: 13, name: 'Salão e Barbearia' },
    { id: 14, name: 'Malas e Bolsas' },
    { id: 15, name: 'Piscinas e Boias' },
    { id: 16, name: 'Saúde e Beleza' },
    { id: 17, name: 'Petshop' },
    { id: 18, name: 'Esportes' },
    { id: 19, name: 'Livraria e Papelaria' },
];

export const getCatName = (id) => {
    let name = '';
    categorias.map(cat => {
        if (cat.id === id) {
            console.log(cat.name);
            name = cat.name;
            return;
        }
    });
    return name;
};


//$$$$$$$$$$$$$$$$$$$$$$$
//$$$$$$(COLEÇÕES)$$$$$$$
//$$$$$$$$$$$$$$$$$$$$$$$

export let COLECOES_SECTION_LIST = [
    {
        title: categorias[0].name,
        data: [
            { id: 1, name: 'Fones com fio' },
            { id: 2, name: 'Fones bluetooth' },
            { id: 3, name: 'Headphone' },
            { id: 4, name: 'Headset' },
            { id: 5, name: 'Headset Gamer' },
            { id: 6, name: 'Headset Infantil' },
            { id: 7, name: 'Fones Ip' },
            { id: 8, name: 'Capas para Fone' },
        ]
    },
    {
        title: categorias[1].name,
        data: [
            { id: 101, name: 'Celulares simples' },
            { id: 102, name: 'Bateria de Celular' },
            { id: 103, name: 'Cabos para Celular' },
            { id: 104, name: 'Carregadores' },
            { id: 105, name: 'Telefone com fio' },
            { id: 106, name: 'Telefone sem fio' },
            { id: 107, name: 'Pelicula Protetora' },
            { id: 108, name: 'Capas Xiaome' },
            { id: 109, name: 'Capas Iphone' },
            { id: 110, name: 'Capas Samsung' },
            { id: 111, name: 'Capas Anti Impacto' },
            { id: 112, name: 'Tripe e Suporte' },
            { id: 113, name: 'Gatilhos e Gamepad' },
            { id: 114, name: 'Acessorios para celular' },
            { id: 115, name: 'Peças para Celular' },
            { id: 116, name: 'Aparelhos para Manutenção' },
        ]
    },
    {
        title: categorias[2].name,
        data: [
            { id: 201, name: 'Armazenamento e Discos Rigidos' },
            { id: 202, name: 'Equipamentos de Rede' },
            { id: 203, name: 'Teclados' },
            { id: 204, name: 'Mouses' },
            { id: 205, name: 'Webcans' },
            { id: 206, name: 'Peças para Computador' },
            { id: 207, name: 'Suportes e Coolers' },
            { id: 208, name: 'MousePads' },
            { id: 209, name: 'Microfone pra Computador' },
            { id: 210, name: 'Acessorios para Pc Gamer' },
            { id: 211, name: 'Caixas de som para Computador' },
            { id: 212, name: 'Cabos para Computador' },
            { id: 213, name: 'Nobreak' },
            { id: 214, name: 'Fonte pra Pc' },
        ]
    },
    {
        title: categorias[3].name,
        data: [
            { id: 301, name: 'Controles para Video game' },
            { id: 302, name: 'Acessorios para Xbox One' },
            { id: 303, name: 'Acessorios para Xbox 360' },
            { id: 304, name: 'Acessorios para Playstation 2' },
            { id: 305, name: 'Acessorios para Playstation 3' },
            { id: 306, name: 'Acessorios para Playstation 4' },
            { id: 307, name: 'Headset para Video game' },
            { id: 308, name: 'Jogos para Video game' },
            { id: 309, name: 'Video games portateis' },
            { id: 310, name: 'Games infantis' },
            { id: 311, name: 'Cabos para Videogame' },
        ]
    },
    {
        title: categorias[4].name,
        data: [
            { id: 401, name: 'Acessorios de Tv' },
            { id: 402, name: 'Antenas de Tv' },
            { id: 403, name: 'Controles de Tv' },
            { id: 404, name: 'Controles de Ar' },
            { id: 405, name: 'Controles de Dvd' },
            { id: 406, name: 'Liquidificadores' },
            { id: 407, name: 'Cafeteiras' },
            { id: 408, name: 'Panelas Eletricas' },
            { id: 409, name: 'Fogões' },
            { id: 410, name: 'Umidificadores' },
            { id: 411, name: 'Trituradores e Processadores' },
            { id: 412, name: 'Ferros de Passar' },
            { id: 413, name: 'Ventiladores' },
            { id: 414, name: 'Sanduicheiras' },
            { id: 415, name: 'Microondas' },
            { id: 416, name: 'Batedeira' },
            { id: 417, name: 'Balanças' },
            { id: 418, name: 'Luzes e Iluminação' },
            { id: 419, name: 'Baterias e Pilhas' },
            { id: 420, name: 'Lanternas' },
            { id: 421, name: 'Tomadas e Extensões' },
            { id: 422, name: 'Massageadores' },
            { id: 423, name: 'Cigarros Eletronicos' },
            { id: 424, name: 'Casa Inteligente' },
            { id: 425, name: 'Sistemas de Seguranças' },
            { id: 426, name: 'Cameras de Monitoramento' },
            { id: 427, name: 'Impressoras' },
        ]
    },
    {
        title: categorias[5].name,
        data: [
            { id: 501, name: 'Som Automotivo' },
            { id: 502, name: 'Cameras Automotivas' },
            { id: 503, name: 'Lampadas Automotivas' },
            { id: 504, name: 'Suportes Automotivos para Celular' },
            { id: 505, name: 'Capas Automotivas' },
            { id: 506, name: 'Aromatizador' },
            { id: 507, name: 'Capas para Banco de Carro' },
            { id: 508, name: 'Tapates de Carro' },
            { id: 509, name: 'Aspirador Automotivo' },
            { id: 510, name: 'Capas para Volante' },
            { id: 511, name: 'Carregador Veicular' },
            { id: 512, name: 'Suporte Veicular de Moto' },
            { id: 513, name: 'GPS Veicular' },
            { id: 514, name: 'Compressor de Ar para Carro' },
        ]
    },
    {
        title: categorias[6].name,
        data: [
            { id: 601, name: 'Relogio a prova dagua' },
            { id: 602, name: 'Relogio Femino' },
            { id: 603, name: 'Relogio Masculino' },
            { id: 604, name: 'Relogio Infantil' },
            { id: 605, name: 'Relogio com Calendario' },
            { id: 606, name: 'Relogio Esportivo' },
            { id: 607, name: 'Kits Relogios' },
            { id: 608, name: 'Relogio Led' },
            { id: 609, name: 'Relogio de Ponteiro' },
            { id: 610, name: 'Relogio de Parede' },
        ]
    },
    {
        title: categorias[7].name,
        data: [
            { id: 701, name: 'Caixas de Som' },
            { id: 702, name: 'Mini Caixas de Som' },
            { id: 703, name: 'Radio a Pilha' },
            { id: 704, name: 'Radio Retro' },
            { id: 705, name: 'Instrumentos musicais' },
            { id: 706, name: 'Mesas de som' },
            { id: 707, name: 'Cabos Para Audio e Som' },
            { id: 708, name: 'Caixas Amplicadas' },
            { id: 709, name: 'Microfone Com fio' },
            { id: 710, name: 'Microfone Sem fio' },
            { id: 711, name: 'Tripe para Caixa e Microfone' },
            { id: 712, name: 'Acessorios para Instrumentos' },
        ]
    },
    {
        title: categorias[8].name,
        data: [
            { id: 801, name: 'SmartWacth a Prova Dagua' },
            { id: 802, name: 'SmartWatch que faz Ligação' },
            { id: 803, name: 'SmartWatch que pega Chip' },
            { id: 804, name: 'SmartBand' },
            { id: 805, name: 'Pulseiras 44mm' },
            { id: 806, name: 'Pulseiras 38mm' },
        ]
    },
    {
        title: categorias[9].name,
        data: [
            { id: 901, name: 'Pop it' },
            { id: 902, name: 'Brinquedos de Pelucia' },
            { id: 903, name: 'Carrinho de controle Remoto' },
            { id: 904, name: 'Pista de Carrinhos' },
            { id: 905, name: 'Carrinhos de brinquedo' },
            { id: 906, name: 'Arma de Agua' },
            { id: 907, name: 'Arma de Dardos' },
            { id: 908, name: 'Jogos de Tabuleiro' },
            { id: 909, name: 'Roupas para Bebes' },
            { id: 910, name: 'Sapatos para Bebes' },
            { id: 911, name: 'Brinquedos para Bebes' },
            { id: 912, name: 'Roupas para Crianças' },
            { id: 913, name: 'Sapatos para Crianças' },
            { id: 914, name: 'Brinquedos para Crianças' },
            { id: 915, name: 'Andadores e Carrinhos' },
            { id: 916, name: 'Artigos de Maternidade' },
            { id: 917, name: 'Bolas e Balões' },
        ]
    },
    {
        title: categorias[10].name,
        data: [
            { id: 1001, name: 'Furadeiras' },
            { id: 1002, name: 'Parafusadeiras' },
            { id: 1003, name: 'Serras Eletricas' },
            { id: 1004, name: 'Marteleres' },
            { id: 1005, name: 'Lixadeira e Esmerilhadeiras' },
            { id: 1006, name: 'Kits de Ferramentas' },
            { id: 1007, name: 'Acessorios para Eletrica' },
            { id: 1008, name: 'Acessorios para Pintura' },
            { id: 1009, name: 'Ferramentas para Construção' },
            { id: 1010, name: 'Alicates' },
            { id: 1011, name: 'Martelos' },
            { id: 1012, name: 'Chaves e Kits' },
        ]
    },
    {
        title: categorias[11].name,
        data: [
            { id: 1101, name: 'Jogos de Panelas' },
            { id: 1102, name: 'Jogos de Talheres' },
            { id: 1103, name: 'Panela de Pressão' },
            { id: 1104, name: 'Bomba de Garrafão' },
            { id: 1105, name: 'Balanças' },
            { id: 1106, name: 'Trituradores Manuais' },
            { id: 1107, name: 'Frigideiras' },
            { id: 1108, name: 'Potes' },
            { id: 1109, name: 'Vasilhas' },
            { id: 1110, name: 'Cesto Organizador' },
            { id: 1111, name: 'Varal e Prendedores' },
            { id: 1112, name: 'Mangueiras' },
            { id: 1113, name: 'Tapetes' },
            { id: 1114, name: 'Luminarias' },
            { id: 1115, name: 'Acessorios para churrasco' },
            { id: 1116, name: 'Pratos' },
            { id: 1117, name: 'Copos e Canecas' },
            { id: 1118, name: 'Jarras' },
            { id: 1119, name: 'Escorredores' },
            { id: 1120, name: 'Porta Retratos' },
            { id: 1121, name: 'Artigos para Banheiro' },
            { id: 1122, name: 'Artigos de Jardim' },
            { id: 1123, name: 'Decoração para Casa' },
        ]
    },
    {
        title: categorias[12].name,
        data: [
            { id: 1201, name: 'Roupas Feminina' },
            { id: 1202, name: 'Roupas Masculinas' },
            { id: 1203, name: 'Roupas Infantis' },
            { id: 1204, name: 'Roupas Intimas para Mulher' },
            { id: 1205, name: 'Fantasias' },
            { id: 1206, name: 'Bonés e Chapeis' },
            { id: 1207, name: 'Oculos' },
            { id: 1208, name: 'Bijuterias' },
            { id: 1209, name: 'Correntes e Pulseiras' },
            { id: 1210, name: 'Semi Joias' },
            { id: 1211, name: 'Cinta Modeladora' },
            { id: 1212, name: 'Tenis e Sapatos' },
            { id: 1213, name: 'Meias' },
            { id: 1214, name: 'Camisas de Time' },
        ]
    },
    {
        title: categorias[13].name,
        data: [
            { id: 1301, name: 'Secadores de Cabelo' },
            { id: 1302, name: 'Chapinhas e Modeladoras' },
            { id: 1303, name: 'Aparador de Barba' },
            { id: 1304, name: 'Maquina de Corte' },
            { id: 1305, name: 'Acessorios para Manicure' },
            { id: 1306, name: 'Depiladores Eletricos' },
            { id: 1307, name: 'Tesoura de Cabelo' },
        ]
    },
    {
        title: categorias[14].name,
        data: [
            { id: 1401, name: 'Mochilas Femininas' },
            { id: 1402, name: 'Mochilas Masculinas' },
            { id: 1403, name: 'Mochilas Infantis' },
            { id: 1404, name: 'Bolsas' },
            { id: 1405, name: 'Polchetes' },
            { id: 1406, name: 'Malas' },
            { id: 1407, name: 'Bolsas Termicas' },
        ]
    },
    {
        title: categorias[15].name,
        data: [
            { id: 1501, name: 'Piscina para Adulto' },
            { id: 1502, name: 'Piscina para Crianças' },
            { id: 1503, name: 'Boias Grandes' },
            { id: 1504, name: 'Boias Pequenas' },
        ]
    },
    {
        title: categorias[16].name,
        data: [
            { id: 1601, name: 'Medidor de Pressão' },
            { id: 1602, name: 'Oximetro' },
            { id: 1603, name: 'Termometro' },
            { id: 1604, name: 'Shakes e Suplementos' },
            { id: 1605, name: 'Vitaminas e Minerais' },
            { id: 1606, name: 'Cosmesticos' },
            { id: 1607, name: 'Perfumes' },
            { id: 1608, name: 'Maquiagens' },
            { id: 1609, name: 'Cilios' },
            { id: 1610, name: 'Acessorios para Maquiagem' },
            { id: 1611, name: 'Mascaras' },
        ]
    }
];


export let COLECOES_LIST = [
    //FONES E HEADSETS
    { id: 1, name: 'Fones com fio' },
    { id: 2, name: 'Fones bluetooth' },
    { id: 3, name: 'Headphone' },
    { id: 4, name: 'Headset' },
    { id: 5, name: 'Headset Gamer' },
    { id: 6, name: 'Headset Infantil' },
    { id: 7, name: 'Fones Ip' },
    { id: 8, name: 'Capas para Fone' },
    //CELULARES
    { id: 101, name: 'Celulares simples' },
    { id: 102, name: 'Bateria de Celular' },
    { id: 103, name: 'Cabos para Celular' },
    { id: 104, name: 'Carregadores' },
    { id: 105, name: 'Telefone com fio' },
    { id: 106, name: 'Telefone sem fio' },
    { id: 107, name: 'Pelicula Protetora' },
    { id: 108, name: 'Capas Xiaome' },
    { id: 109, name: 'Capas Iphone' },
    { id: 110, name: 'Capas Samsung' },
    { id: 111, name: 'Capas Anti Impacto' },
    { id: 112, name: 'Tripe e Suporte' },
    { id: 113, name: 'Gatilhos e Gamepad' },
    { id: 114, name: 'Acessorios para celular' },
    { id: 115, name: 'Peças para Celular' },
    { id: 116, name: 'Aparelhos para Manutenção' },
    //INFORMATICA
    { id: 201, name: 'Armazenamento e Discos Rigidos' },
    { id: 202, name: 'Equipamentos de Rede' },
    { id: 203, name: 'Teclados' },
    { id: 204, name: 'Mouses' },
    { id: 205, name: 'Webcans' },
    { id: 206, name: 'Peças para Computador' },
    { id: 207, name: 'Suportes e Coolers' },
    { id: 208, name: 'MousePads' },
    { id: 209, name: 'Microfone pra Computador' },
    { id: 210, name: 'Acessorios para Pc Gamer' },
    { id: 211, name: 'Caixas de som para Computador' },
    { id: 212, name: 'Cabos para Computador' },
    { id: 213, name: 'Nobreak' },
    { id: 214, name: 'Fonte pra Pc' },
    //VIDEO GAME
    { id: 301, name: 'Controles para Video game' },
    { id: 302, name: 'Acessorios para Xbox One' },
    { id: 303, name: 'Acessorios para Xbox 360' },
    { id: 304, name: 'Acessorios para Playstation 2' },
    { id: 305, name: 'Acessorios para Playstation 3' },
    { id: 306, name: 'Acessorios para Playstation 4' },
    { id: 307, name: 'Headset para Video game' },
    { id: 308, name: 'Jogos para Video game' },
    { id: 309, name: 'Video games portateis' },
    { id: 310, name: 'Games infantis' },
    { id: 311, name: 'Cabos para Videogame' },
    //ELETRONICOS
    { id: 401, name: 'Acessorios de Tv' },
    { id: 402, name: 'Antenas de Tv' },
    { id: 403, name: 'Controles de Tv' },
    { id: 404, name: 'Controles de Ar' },
    { id: 405, name: 'Controles de Dvd' },
    { id: 406, name: 'Liquidificadores' },
    { id: 407, name: 'Cafeteiras' },
    { id: 408, name: 'Panelas Eletricas' },
    { id: 409, name: 'Fogões' },
    { id: 410, name: 'Umidificadores' },
    { id: 411, name: 'Trituradores e Processadores' },
    { id: 412, name: 'Ferros de Passar' },
    { id: 413, name: 'Ventiladores' },
    { id: 414, name: 'Sanduicheiras' },
    { id: 415, name: 'Microondas' },
    { id: 416, name: 'Batedeira' },
    { id: 417, name: 'Balanças' },
    { id: 418, name: 'Luzes e Iluminação' },
    { id: 419, name: 'Baterias e Pilhas' },
    { id: 420, name: 'Lanternas' },
    { id: 421, name: 'Tomadas e Extensões' },
    { id: 422, name: 'Massageadores' },
    { id: 423, name: 'Cigarros Eletronicos' },
    { id: 424, name: 'Casa Inteligente' },
    { id: 425, name: 'Sistemas de Seguranças' },
    { id: 426, name: 'Cameras de Monitoramento' },
    { id: 427, name: 'Impressoras' },
    //AUTOMOTIVOS
    { id: 501, name: 'Som Automotivo' },
    { id: 502, name: 'Cameras Automotivas' },
    { id: 503, name: 'Lampadas Automotivas' },
    { id: 504, name: 'Suportes Automotivos para Celular' },
    { id: 505, name: 'Capas Automotivas' },
    { id: 506, name: 'Aromatizador' },
    { id: 507, name: 'Capas para Banco de Carro' },
    { id: 508, name: 'Tapates de Carro' },
    { id: 509, name: 'Aspirador Automotivo' },
    { id: 510, name: 'Capas para Volante' },
    { id: 511, name: 'Carregador Veicular' },
    { id: 512, name: 'Suporte Veicular de Moto' },
    { id: 513, name: 'GPS Veicular' },
    { id: 514, name: 'Compressor de Ar para Carro' },
    //RELOGIOS
    { id: 601, name: 'Relogio a prova dagua' },
    { id: 602, name: 'Relogio Femino' },
    { id: 603, name: 'Relogio Masculino' },
    { id: 604, name: 'Relogio Infantil' },
    { id: 605, name: 'Relogio com Calendario' },
    { id: 606, name: 'Relogio Esportivo' },
    { id: 607, name: 'Kits Relogios' },
    { id: 608, name: 'Relogio Led' },
    { id: 609, name: 'Relogio de Ponteiro' },
    { id: 610, name: 'Relogio de Parede' },
    //CAIXAS DE SOM
    { id: 701, name: 'Caixas de Som' },
    { id: 702, name: 'Mini Caixas de Som' },
    { id: 703, name: 'Radio a Pilha' },
    { id: 704, name: 'Radio Retro' },
    { id: 705, name: 'Instrumentos musicais' },
    { id: 706, name: 'Mesas de som' },
    { id: 707, name: 'Cabos Para Audio e Som' },
    { id: 708, name: 'Caixas Amplicadas' },
    { id: 709, name: 'Microfone Com fio' },
    { id: 710, name: 'Microfone Sem fio' },
    { id: 711, name: 'Tripe para Caixa e Microfone' },
    { id: 712, name: 'Acessorios para Instrumentos' },
    //SMARTWATCH
    { id: 801, name: 'SmartWacth a Prova Dagua' },
    { id: 802, name: 'SmartWatch que faz Ligação' },
    { id: 803, name: 'SmartWatch que pega Chip' },
    { id: 804, name: 'SmartBand' },
    { id: 805, name: 'Pulseiras 44mm' },
    { id: 806, name: 'Pulseiras 38mm' },
    //BEBES E CRIANÇAS
    { id: 901, name: 'Pop it' },
    { id: 902, name: 'Brinquedos de Pelucia' },
    { id: 903, name: 'Carrinho de controle Remoto' },
    { id: 904, name: 'Pista de Carrinhos' },
    { id: 905, name: 'Carrinhos de brinquedo' },
    { id: 906, name: 'Arma de Agua' },
    { id: 907, name: 'Arma de Dardos' },
    { id: 908, name: 'Jogos de Tabuleiro' },
    { id: 909, name: 'Roupas para Bebes' },
    { id: 910, name: 'Sapatos para Bebes' },
    { id: 911, name: 'Brinquedos para Bebes' },
    { id: 912, name: 'Roupas para Crianças' },
    { id: 913, name: 'Sapatos para Crianças' },
    { id: 914, name: 'Brinquedos para Crianças' },
    { id: 915, name: 'Andadores e Carrinhos' },
    { id: 916, name: 'Artigos de Maternidade' },
    { id: 917, name: 'Bolas e Balões' },
    //FERRAMENTAS
    { id: 1001, name: 'Furadeiras' },
    { id: 1002, name: 'Parafusadeiras' },
    { id: 1003, name: 'Serras Eletricas' },
    { id: 1004, name: 'Marteleres' },
    { id: 1005, name: 'Lixadeira e Esmerilhadeiras' },
    { id: 1006, name: 'Kits de Ferramentas' },
    { id: 1007, name: 'Acessorios para Eletrica' },
    { id: 1008, name: 'Acessorios para Pintura' },
    { id: 1009, name: 'Ferramentas para Construção' },
    { id: 1010, name: 'Alicates' },
    { id: 1011, name: 'Martelos' },
    { id: 1012, name: 'Chaves e Kits' },
    //CASA E COZINHA
    { id: 1101, name: 'Jogos de Panelas' },
    { id: 1102, name: 'Jogos de Talheres' },
    { id: 1103, name: 'Panela de Pressão' },
    { id: 1104, name: 'Bomba de Garrafão' },
    { id: 1105, name: 'Balanças' },
    { id: 1106, name: 'Trituradores Manuais' },
    { id: 1107, name: 'Frigideiras' },
    { id: 1108, name: 'Potes' },
    { id: 1109, name: 'Vasilhas' },
    { id: 1110, name: 'Cesto Organizador' },
    { id: 1111, name: 'Varal e Prendedores' },
    { id: 1112, name: 'Mangueiras' },
    { id: 1113, name: 'Tapetes' },
    { id: 1114, name: 'Luminarias' },
    { id: 1115, name: 'Acessorios para churrasco' },
    { id: 1116, name: 'Pratos' },
    { id: 1117, name: 'Copos e Canecas' },
    { id: 1118, name: 'Jarras' },
    { id: 1119, name: 'Escorredores' },
    { id: 1120, name: 'Porta Retratos' },
    { id: 1121, name: 'Artigos para Banheiro' },
    { id: 1122, name: 'Artigos de Jardim' },
    { id: 1123, name: 'Decoração para Casa' },
    //MODA E ACESSORIOS
    { id: 1201, name: 'Roupas Feminina' },
    { id: 1202, name: 'Roupas Masculinas' },
    { id: 1203, name: 'Roupas Infantis' },
    { id: 1204, name: 'Roupas Intimas para Mulher' },
    { id: 1205, name: 'Fantasias' },
    { id: 1206, name: 'Bonés e Chapeis' },
    { id: 1207, name: 'Oculos' },
    { id: 1208, name: 'Bijuterias' },
    { id: 1209, name: 'Correntes e Pulseiras' },
    { id: 1210, name: 'Semi Joias' },
    { id: 1211, name: 'Cinta Modeladora' },
    { id: 1212, name: 'Tenis e Sapatos' },
    { id: 1213, name: 'Meias' },
    { id: 1214, name: 'Camisas de Time' },
    //SALAO E BARBEARIA
    { id: 1301, name: 'Secadores de Cabelo' },
    { id: 1302, name: 'Chapinhas e Modeladoras' },
    { id: 1303, name: 'Aparador de Barba' },
    { id: 1304, name: 'Maquina de Corte' },
    { id: 1305, name: 'Acessorios para Manicure' },
    { id: 1306, name: 'Depiladores Eletricos' },
    { id: 1307, name: 'Tesoura de Cabelo' },
    //MALAS E BOLSAS
    { id: 1401, name: 'Mochilas Femininas' },
    { id: 1402, name: 'Mochilas Masculinas' },
    { id: 1403, name: 'Mochilas Infantis' },
    { id: 1404, name: 'Bolsas' },
    { id: 1405, name: 'Polchetes' },
    { id: 1406, name: 'Malas' },
    { id: 1407, name: 'Bolsas Termicas' },
    //PISCINAS E BOIAS
    { id: 1501, name: 'Piscina para Adulto' },
    { id: 1502, name: 'Piscina para Crianças' },
    { id: 1503, name: 'Boias Grandes' },
    { id: 1504, name: 'Boias Pequenas' },
    //SAUDE E BELEZA
    { id: 1601, name: 'Medidor de Pressão' },
    { id: 1602, name: 'Oximetro' },
    { id: 1603, name: 'Termometro' },
    { id: 1604, name: 'Shakes e Suplementos' },
    { id: 1605, name: 'Vitaminas e Minerais' },
    { id: 1606, name: 'Cosmesticos' },
    { id: 1607, name: 'Perfumes' },
    { id: 1608, name: 'Maquiagens' },
    { id: 1609, name: 'Cilios' },
    { id: 1610, name: 'Acessorios para Maquiagem' },
    { id: 1611, name: 'Mascaras' },
    //

];

export const getCollName = (id) => {
    let name = ''
    COLECOES_LIST.map(coll => {
        if (coll.id === id) {
            console.log(coll.name);
            name = coll.name;
            return;
        }
    });

    return name;
};